version: "3"

volumes:
  postgres_data:

services:

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
